library(rgpdd)
library(dplyr)
library(raster)
library(rgdal)

#Read in average monthly temperatures from WorldClim (Hijmans, R. J. et al. 2005. Very high resoluction interpolated climate surfaces for flobal land areas.)
#Data is in degrees celcius * 10.
temp_1_data <- raster("./tmean_10m_bil/tmean1.bil")
temp_2_data <- raster("./tmean_10m_bil/tmean2.bil")
temp_3_data <- raster("./tmean_10m_bil/tmean3.bil")
temp_4_data <- raster("./tmean_10m_bil/tmean4.bil")
temp_5_data <- raster("./tmean_10m_bil/tmean5.bil")
temp_6_data <- raster("./tmean_10m_bil/tmean6.bil")
temp_7_data <- raster("./tmean_10m_bil/tmean7.bil")
temp_8_data <- raster("./tmean_10m_bil/tmean8.bil")
temp_9_data <- raster("./tmean_10m_bil/tmean9.bil")
temp_10_data <- raster("./tmean_10m_bil/tmean10.bil")
temp_11_data <- raster("./tmean_10m_bil/tmean11.bil")
temp_12_data <- raster("./tmean_10m_bil/tmean12.bil")

temp_1_data_df <- rasterToPoints(temp_1_data) %>% data.frame()
temp_2_data_df <- rasterToPoints(temp_2_data) %>% data.frame()
temp_3_data_df <- rasterToPoints(temp_3_data) %>% data.frame()
temp_4_data_df <- rasterToPoints(temp_4_data) %>% data.frame()
temp_5_data_df <- rasterToPoints(temp_5_data) %>% data.frame()
temp_6_data_df <- rasterToPoints(temp_6_data) %>% data.frame()
temp_7_data_df <- rasterToPoints(temp_7_data) %>% data.frame()
temp_8_data_df <- rasterToPoints(temp_8_data) %>% data.frame()
temp_9_data_df <- rasterToPoints(temp_9_data) %>% data.frame()
temp_10_data_df <- rasterToPoints(temp_10_data) %>% data.frame()
temp_11_data_df <- rasterToPoints(temp_11_data) %>% data.frame()
temp_12_data_df <- rasterToPoints(temp_12_data) %>% data.frame()

colnames(temp_1_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_2_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_3_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_4_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_5_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_6_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_7_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_8_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_9_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_10_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_11_data_df)[1:2] <- c("Long", "Lat") 
colnames(temp_12_data_df)[1:2] <- c("Long", "Lat") 
nrow(temp_12_data_df)

#amalgamate data frames. Because I don't know of a better way, I iteratively add df's to the main df "monthly_temp_df"
#I join by longitude, then filter out the duplicate values
monthly_temp_df <- left_join(temp_1_data_df, temp_2_data_df, by = "Long") %>% filter(Lat.x == Lat.y)
monthly_temp_df <- monthly_temp_df %>% dplyr::select(Long, Lat.x, tmean1, tmean2)
monthly_temp_df <- left_join(monthly_temp_df, temp_3_data_df, by = "Long")
monthly_temp_df <- monthly_temp_df %>% filter(Lat.x == Lat) %>% dplyr::select(Long, Lat, tmean1, tmean2, tmean3)
monthly_temp_df <- left_join(monthly_temp_df, temp_4_data_df, by = "Long")  
monthly_temp_df <- monthly_temp_df %>% filter(Lat.x == Lat.y) %>% dplyr::select(Long, Lat.x, tmean1, tmean2, tmean3, tmean4)
monthly_temp_df <- left_join(monthly_temp_df, temp_5_data_df, by = "Long")
monthly_temp_df <- monthly_temp_df %>% filter(Lat.x == Lat) %>% dplyr::select(Long, Lat, tmean1, tmean2, tmean3, tmean4, tmean5)
monthly_temp_df <- left_join(monthly_temp_df, temp_6_data_df, by = "Long")
monthly_temp_df <- monthly_temp_df %>% filter(Lat.x == Lat.y) %>% dplyr::select(Long, Lat.x, tmean1, tmean2, tmean3, tmean4, tmean5, tmean6)
monthly_temp_df <- left_join(monthly_temp_df, temp_7_data_df, by = "Long")
monthly_temp_df <- monthly_temp_df %>% filter(Lat.x == Lat) %>% dplyr::select(Long, Lat, tmean1, tmean2, tmean3, tmean4, tmean5, tmean6, tmean7)
monthly_temp_df <- left_join(monthly_temp_df, temp_8_data_df, by = "Long")
monthly_temp_df <- monthly_temp_df %>% filter(Lat.x == Lat.y) %>% dplyr::select(Long, Lat.x, tmean1, tmean2, tmean3, tmean4, tmean5, tmean6, tmean7, tmean8)
monthly_temp_df <- left_join(monthly_temp_df, temp_9_data_df, by = "Long")

head(monthly_temp_df)
#I'm interested in 2 values for terrestrial organisms: average annual temperature, and average temperatures during the "growing season," April - October in Northern latitudes.

avg_annual_temp <- mean(temp_1_data_df, temp_2_data_df, temp_3_data_df, temp_4_data_df, temp_5_data_df, temp_6_data_df, temp_7_data_df, temp_8_data_df, temp_9_data_df, temp_10_data_df, temp_11_data_df, temp_12_data_df)
plot(avg_annual_temp / 10)
